"""Generate a Markdown comment from an Assay gate JSON report.

Usage:
    python scripts/pr_comment.py report.json

Reads the JSON report and prints a Markdown comment suitable for a
GitHub pull request. The comment is written to stdout.
"""

import argparse
import json
import sys
from pathlib import Path


def _format_value(value: float | None, unit: str = "") -> str:
    """Format a numeric value for display."""
    if value is None:
        return "N/A"
    if unit == "%":
        return f"{value:+.1f}%"
    if unit == "ms":
        return f"{value:.0f}ms"
    if unit == "usd":
        return f"${value:.4f}"
    return f"{value:.3f}"


def _format_delta_pct(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"{value:+.1f}%"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", help="Path to JSON report")
    args = parser.parse_args()

    path = Path(args.report)
    if not path.exists():
        print(f"Report file not found: {path}", file=sys.stderr)
        sys.exit(2)

    with path.open(encoding="utf-8") as f:
        report = json.load(f)

    passed = report.get("passed", False)
    verdict_emoji = "✅" if passed else "❌"
    verdict_text = "PASSED" if passed else "FAILED"

    lines: list[str] = []
    lines.append("## Assay Regression Report")
    lines.append("")
    lines.append(f"**{verdict_emoji} {verdict_text}**")
    lines.append("")

    baseline = report.get("baseline_name", "unknown")
    baseline_run = report.get("baseline_run_id", "?")
    current_run = report.get("current_run_id", "?")
    lines.append(f"Baseline: `{baseline}` (run {baseline_run})")
    lines.append(f"Current: run {current_run}")
    lines.append("")

    # Metrics table
    lines.append("| Metric | Baseline | Current | Δ abs | Δ % | Status |")
    lines.append("|---|---|---|---|---|---|")

    for m in report.get("metrics", []):
        name = m.get("name", "?")
        base = m.get("baseline")
        curr = m.get("current")
        delta_abs = m.get("delta_absolute")
        delta_pct = m.get("delta_percent")
        passed_m = m.get("passed")

        base_str = f"{base:.3f}" if base is not None else "N/A"
        curr_str = f"{curr:.3f}" if curr is not None else "N/A"
        abs_str = f"{delta_abs:+.3f}" if delta_abs is not None else "N/A"
        pct_str = _format_delta_pct(delta_pct)

        if passed_m is True:
            status = "✅ PASS"
        elif passed_m is False:
            status = "❌ FAIL"
        else:
            status = "-"

        lines.append(
            f"| `{name}` | {base_str} | {curr_str} | {abs_str} | {pct_str} | {status} |"
        )

    lines.append("")

    # Reasons
    reasons = report.get("reasons", [])
    if reasons:
        lines.append("### Why it failed")
        lines.append("")
        for r in reasons:
            lines.append(f"- {r}")
        lines.append("")

    # Worst failures
    failures = report.get("worst_failures", [])
    if failures:
        lines.append(f"### Worst failures ({len(failures)})")
        lines.append("")
        for f in failures:
            qid = f.get("question_id", "?")
            qtext = f.get("question", "")
            base = f.get("baseline")
            curr = f.get("current")
            delta = f.get("delta")

            # Truncate question text
            if len(qtext) > 80:
                qtext = qtext[:77] + "..."

            base_str = f"{base:.2f}" if base is not None else "N/A"
            curr_str = f"{curr:.2f}" if curr is not None else "N/A"
            delta_str = f"{delta:+.2f}" if delta is not None else "N/A"

            lines.append(f"- Q{qid}: \"{qtext}\"")
            lines.append(f"  - {base_str} → {curr_str} (delta {delta_str})")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by [Assay](https://github.com/gigihsusetyo/assay), "
        "a CI gate for RAG quality regressions._"
    )

    print("\n".join(lines))


if __name__ == "__main__":
    main()
