"""Probe self-preference bias in the LLM-as-judge.

Self-preference bias is when a judge gives higher scores to answers
generated by the same model it uses, compared to answers from a
different model.

This script:

1. Takes a calibration set.
2. Generates an answer for each question using Provider A (Groq).
3. Generates an answer for each question using Provider B (Gemini).
4. Judges both answers with Provider A and Provider B.
5. Compares the scores.

If Provider A consistently scores its own answer higher than Provider B's
answer, it has self-preference bias.

Requires two providers configured via environment files:
    .env.groq    (or main .env)
    .env.gemini

Usage:
    python scripts/probe_self_preference_bias.py examples/calibration_set.json
"""

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path

# Import after env setup is done per-provider.
# We will re-import config settings inside functions.


@dataclass
class ProviderConfig:
    """Configuration for a single LLM provider."""

    name: str
    env_file: str


PROVIDERS = [
    ProviderConfig(name="groq", env_file=".env"),
    ProviderConfig(name="gemini", env_file=".env.gemini"),
]


def _load_provider_env(env_file: str) -> None:
    """Load environment variables from the given file, overriding current."""
    from dotenv import load_dotenv

    if not Path(env_file).exists():
        raise SystemExit(f"Env file not found: {env_file}")
    load_dotenv(env_file, override=True)
    # Force settings reload by clearing cached module
    for mod in list(sys.modules.keys()):
        if mod.startswith("assay.config"):
            del sys.modules[mod]


def _get_settings():
    """Get a fresh Settings instance after env reload."""
    # Import fresh
    from assay.config import Settings

    return Settings(_env_file=None)


def _get_judge():
    """Get a fresh judge function after env reload."""
    for mod in list(sys.modules.keys()):
        if mod.startswith("assay.core.metrics.judge"):
            del sys.modules[mod]
    from assay.core.metrics.judge import judge_groundedness

    return judge_groundedness


def _generate_answer(question: str, contexts: list[str]) -> str:
    """Use the current provider to generate an answer to the question."""
    from openai import OpenAI

    settings = _get_settings()
    if not settings.judge_enabled:
        raise RuntimeError("Judge not configured")

    client = OpenAI(
        api_key=settings.judge_api_key,
        base_url=settings.judge_base_url,
        timeout=settings.judge_timeout,
    )

    context_text = "\n\n".join(f"[{i + 1}] {c}" for i, c in enumerate(contexts))
    prompt = (
        "Answer the following question using only the provided contexts. "
        "Be concise. If the contexts do not contain the answer, say so.\n\n"
        f"Question:\n{question}\n\n"
        f"Contexts:\n{context_text}\n\n"
        "Answer:"
    )

    response = client.chat.completions.create(
        model=settings.judge_model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )
    return (response.choices[0].message.content or "").strip()


def _load_calibration_set(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    entries = data.get("entries", [])
    if not entries:
        raise SystemExit("Calibration set has no entries")
    return entries


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("calibration_set", help="Calibration set JSON file")
    parser.add_argument(
        "--limit", type=int, default=5, help="Max entries to test (default: 5)"
    )
    args = parser.parse_args()

    path = Path(args.calibration_set)
    if not path.exists():
        raise SystemExit(f"File not found: {path}")

    entries = _load_calibration_set(path)[: args.limit]

    print("=" * 60)
    print("Self-Preference Bias Probe")
    print("=" * 60)
    print()
    print(f"Testing {len(entries)} entries with providers:")
    for p in PROVIDERS:
        print(f"  - {p.name} ({p.env_file})")
    print()

    # Step 1: Generate answers from each provider
    generated: dict[str, list[str]] = {p.name: [] for p in PROVIDERS}

    for provider in PROVIDERS:
        print(f"Generating answers with {provider.name}...")
        _load_provider_env(provider.env_file)
        for i, entry in enumerate(entries):
            try:
                answer = _generate_answer(
                    entry["question"], entry.get("contexts", [])
                )
                generated[provider.name].append(answer)
                print(f"  Entry {i + 1}: {answer[:60]}...")
            except Exception as e:
                print(f"  Entry {i + 1}: FAILED ({e})")
                generated[provider.name].append("")
        print()

    # Step 2: Judge each generated answer with each provider
    scores: dict[tuple[str, str], list[float]] = {}

    for judge_provider in PROVIDERS:
        print(f"Judging with {judge_provider.name}...")
        _load_provider_env(judge_provider.env_file)
        judge = _get_judge()

        for answer_provider in PROVIDERS:
            key = (judge_provider.name, answer_provider.name)
            scores[key] = []

            for i, entry in enumerate(entries):
                answer = generated[answer_provider.name][i]
                if not answer:
                    scores[key].append(0.0)
                    continue
                try:
                    result = judge(
                        entry["question"], answer, entry.get("contexts", [])
                    )
                    scores[key].append(result.score)
                    # Print reason for cross-judge cases (different provider)
                    if judge_provider.name != answer_provider.name:
                        print(
                            f"  Entry {i + 1}: judge={result.score:.2f}, "
                            f"reason={result.reason[:120]}"
                        )
                except Exception as e:
                    print(f"  Entry {i + 1}: judge failed ({e})")
                    scores[key].append(0.0)
        print()

    # Step 3: Analyze
    print("=" * 60)
    print("Results")
    print("=" * 60)
    print()

    for judge_provider in PROVIDERS:
        print(f"Judge: {judge_provider.name}")
        for answer_provider in PROVIDERS:
            key = (judge_provider.name, answer_provider.name)
            avg = sum(scores[key]) / len(scores[key]) if scores[key] else 0.0
            print(
                f"  Answers from {answer_provider.name:8s}: avg score = {avg:.3f}"
            )
        print()

    # Self-preference: for each judge, compare score of own vs other
    print("Self-Preference Check:")
    for judge_provider in PROVIDERS:
        own_key = (judge_provider.name, judge_provider.name)
        own_avg = sum(scores[own_key]) / len(scores[own_key]) if scores[own_key] else 0.0

        other_scores: list[float] = []
        for answer_provider in PROVIDERS:
            if answer_provider.name == judge_provider.name:
                continue
            other_key = (judge_provider.name, answer_provider.name)
            other_scores.extend(scores[other_key])

        other_avg = sum(other_scores) / len(other_scores) if other_scores else 0.0
        diff = own_avg - other_avg

        print(f"  {judge_provider.name}:")
        print(f"    Own answers avg:   {own_avg:.3f}")
        print(f"    Other answers avg: {other_avg:.3f}")
        print(f"    Difference:        {diff:+.3f}")
        if abs(diff) < 0.1:
            print("    Interpretation: NO SELF-PREFERENCE")
        elif diff > 0:
            print("    Interpretation: SELF-PREFERENCE DETECTED")
        else:
            print("    Interpretation: OTHER-PREFERENCE (unusual)")
        print()


if __name__ == "__main__":
    main()
